version: "3.7"
services:
  trino:
    image: trinodb/trino:351
    env_file:
      - .dockerenv
    volumes:
      - "./trino-config-docker/etc:/etc/trino"
      - "./trino-config-docker/plugin/trino-events:/usr/lib/trino/plugin/trino-events"
    ports:
      - "${TRINO_PORT:-8080}:8080"
  redis:
    image: redis
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
  superset:
    image: apache/superset
    volumes:
      - "./superset-config-docker/etc:/etc/superset"
    ports:
      - "${SUPERSET_PORT:-8088}:8088"
